### ISSUE TITLE
sensor: statetable full

### ISSUE THREAD

**Issue by nl5887** [honeytrap/honeytrap#283]
```
panic: Statetable full

goroutine 30 [running]:
github.com/honeytrap/honeytrap/listener/canary.(*StateTable).Add(0xc4268220a8, 0xc4474e4820)
        /Users/remco/Projects/honeytrap/honeytrap/src/github.com/honeytrap/honeytrap/listener/canary/state.go:140 +0x93
github.com/honeytrap/honeytrap/listener/canary.(*Canary).handleTCP(0xc426822000, 0xc44fd533b0, 0xc448f300b0, 0xc42692e022, 0x14, 0xffdd, 0x0, 0x0)
        /Users/remco/Projects/honeytrap/honeytrap/src/github.com/honeytrap/honeytrap/listener/canary/canary_linux.go:333 +0xad1
github.com/honeytrap/honeytrap/listener/canary.(*Canary).Start.func2(0xc426822000, 0xc426928000, 0xc42692e000)
        /Users/remco/Projects/honeytrap/honeytrap/src/github.com/honeytrap/honeytrap/listener/canary/canary_linux.go:1069 +0x7b5
created by github.com/honeytrap/honeytrap/listener/canary.(*Canary).Start
        /Users/remco/Projects/honeytrap/honeytrap/src/github.com/honeytrap/honeytrap/listener/canary/canary_linux.go:1027 +0xed
```

**Comment by nl5887** [comment]
#343
